// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {define} from '../models';

export function ConnectionCreate(arg1:define.Connection):Promise<any>;

export function ConnectionDelete(arg1:string):Promise<any>;

export function ConnectionEdit(arg1:define.Connection):Promise<any>;

export function ConnectionList():Promise<any>;

export function DbList(arg1:string):Promise<any>;

export function GetKeyValue(arg1:define.KeyValueRequest):Promise<any>;

export function KeyList(arg1:define.KeyListRequest):Promise<any>;
